import { generateText } from "ai"

export const maxDuration = 60

export async function POST(req: Request) {
  try {
    const { faceImage, hairDescription } = await req.json()

    if (!faceImage || !hairDescription) {
      return Response.json({ error: "Missing required fields" }, { status: 400 })
    }

    const { text, files } = await generateText({
      model: "google/gemini-2.5-flash-image",
      messages: [
        {
          role: "user",
          content: [
            {
              type: "image",
              image: new Uint8Array(Buffer.from(faceImage.split(",")[1], "base64")),
            },
            {
              type: "text",
              text: `You are a professional hairstylist and image editor. Take this face photo and apply the following hairstyle to it: "${hairDescription}"

IMPORTANT INSTRUCTIONS:
- Keep the same person's face and facial features
- Only modify the hairstyle/hair
- Maintain the original skin tone, face shape, and facial features
- Apply the described hairstyle realistically to this specific person
- Use professional photography lighting and quality
- Make it look natural and realistic

Generate the edited image with the new hairstyle applied to this person.`,
            },
          ],
        },
      ],
    })

    let imageUrl: string | null = null

    if (files && files.length > 0) {
      for (const file of files) {
        if (file.mediaType.startsWith("image/")) {
          imageUrl = `data:${file.mediaType};base64,${file.base64}`
          break
        }
      }
    }

    if (!imageUrl) {
      throw new Error("No image was generated by Gemini")
    }

    return Response.json({ imageUrl })
  } catch (error) {
    console.error("Error generating hairstyle:", error)
    const errorMessage = error instanceof Error ? error.message : "Failed to generate hairstyle"
    return Response.json({ error: errorMessage }, { status: 500 })
  }
}
